### ISSUE TITLE
Enhance e.g. #software table with sortability

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDDN#103]
The tables for 'Software' are sorted on 'Total hits' descending.  When making a new release of a software it's more interesting to look at the 'Today' and 'Yesterday' hits numbers.  Obviously this can be done by eye, but it would be more convenient if a user could click on the requisite column heading to have the sorting switch to it (and toggle ascending/descending if already selected).

Obviously then either the Highchart pie chart would need some labelling *or* even better, switch to the selected column's data.

The same could be applied to the Schemas data table.

**Comment by kenneaal** [comment]
A potential alternative for this is jsGrid, which is a quick and easy way to get sortable, event-capable data grids. http://js-grid.com/ is the site. Using the static data source method (Just feed an array to data: ), getting a sortable grid is 21 lines of JS.

**Comment by Athanasius** [comment]
See https://github.com/EDSM-NET/EDDN/pull/104

**Comment by Athanasius** [comment]
The PR has long since been merged and working well.
