### ISSUE TITLE
Detect DUPLICATE in Gateway so uploading software can alert user

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDDN#106]
The Monitor (for the stats) and Relay (to save outbound bandwidth) detect if a message is a duplicate based on recent messages.

If the Gateway also did this detection then it could return a HTTP status code and message to tell the uploading software that the user likely has another software also sending to EDDN (it might also be a rather quick replay).  Then the software could choose to inform the user so that they can change settings to ensure they're only sending each message to EDDN once.

The changes to Gateway.py should be fairly simple, but we need:

- [ ] To agree on the HTTP status code, and any in-body message.
- [ ] Have the major softwares set up to properly handle this, so as to not spam the user with an error per EDDN message.

**Comment by richardbuckle** [comment]
Maybe [208 Already Reported](https://httpstatuses.com/208).

**Comment by Athanasius** [comment]
If the duplicate detection is moved to only be in the Gateway then:

1. No need to pass those messages to the Relay at all
1. A minimal message can be passed to the Monitor for it to record it in the stats.

So this would actually reduce the amount of CPU time (and RAM?) spent on detecting duplicates.
