### ISSUE TITLE
[Enhancement] Send NavRoute data on journal schema.

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDDN#109]
The `NavRoute.json` file, written when a journal `NavRoute` event occurs, contains:

1. System Name
1. System co-ordinates
1. SystemAddress (id64)
1. Main star's class

for each step in the plotted route.  It would be simple to take the `route` array out of the file and insert it into the journal event before sending that over EDDN.  Then any listeners could choose to utilise it to potentially gain co-ordinates and systemaddress for extra systems.

As the provided data in the route array is what is currently required as the bare minimum in a journal schema message this shouldn't actually require any changes to the schema other than adding the event type to the allowed list.  This issue mostly for reference and any further discussion.  It would require a small update to the documentation to explicitly state that the route array needs adding from the file.

**Comment by Tkael** [comment]
Superseded / replaced by #133.
