### ISSUE TITLE
Schemas/Journal: ApproachSettlement

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDDN#131]
It is proposed that the `ApproachSettlement` event be allowed in the Journal schema.

Please discuss any objections, caveats or possible problems with this.

**Comment by Tkael** [comment]
Augmented with SystemName and StarPos I'd imagine.

**Comment by Athanasius** [comment]
As per current policy this events should not be added to the journal schema, but instead to its own schema.

**Comment by Athanasius** [comment]
This schema is now present in the `beta` branch is available for testing on the beta service:

Upload: `https://beta.eddn.edcd.io:4431/upload/`
Listen: `tcp://beta.eddn.edcd.io:9510/`
