### ISSUE TITLE
Update to latest JSON schema version(s)

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDDN#139]
We're still specifying and using JSON schema v4, which is working for us.

But check if there's any reason to move to the latest / not be on this old version.

**Comment by klightspeed** [comment]
It looks like the major breaking changes in 2019-09 and 2020-12 include:
* `definitions` is renamed to `$defs`
* `id` is renamed to `$id`

**Comment by robbyxp1** [comment]
If it affects the clients, lets not.
