### ISSUE TITLE
Document updates needed including Schemas

### ISSUE THREAD

**Issue by robbyxp1** [EDCD/EDDN#172]
Noted missing:
NavBeaconScan: Missing SystemAddress
CodexEntry: Missing SystemAddress, System
FSSDiscoveryScan: Missing SystemAddress, SystemName,

All are missing "event" from the .md

**Comment by robbyxp1** [comment]
Also, we need to state to use 4 spaces not tabs
And that to add new schemas you need to update src/eddn/conf/Settings.py in Readme.

**Comment by Athanasius** [comment]
I believe this is all covered in #178
