### ISSUE TITLE
Schema: fssbodysignals/1

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDDN#187]
We've got some work on this already in `develop`, and now `beta`, see #185 #186

Aymeric45 has already identified that we have `SystemName` cited as a required field in the schema, and yet this isn't in the original Journal events.  It's not at this time mentioned as a mandatory augmentation in the README.

However, given we have `SystemAddress` in the source Journal events I feel that should be sufficient, and would rather just remove `SystemName` from this schema.

We've seen recent issues with, assumed to be related to the game intermittently not writing journal events to the file, with an EDMC augmentation adding the wrong `StarPos` to a message because there was no `Location` / `CarrierJump` / `FSDJump` event to tell EDMC the system had changed.  Thus going forwards I'd rather not have augmentations in new schemas unless they're 100% necessary for functionality.

**Comment by Athanasius** [comment]
If we're going to continue having augmentations, and certainly adding them to this, and future, new schemas, there is merit to Syleo's idea to use a different keyname, i.e. `aug_StarPos`, not `StarPos`, so that it's crystal clear (without constantly checking the documentation) which data is possibly not to be trusted.

**Comment by aymeric45** [comment]
Why not put these fields under a single key ?
```
```json
{
  "timestamp": "2022-05-24T13:47:35Z",
  "event": "FSSBodySignals",
  "BodyName": "Eock Prau YY-S d3-1 C 1",
  "BodyID": 20,
  "SystemAddress": 50339778851,
  "Signals": [
    {
      "Type": "$SAA_SignalType_Geological;",
      "Type_Localised": "Geological",
      "Count": 2
    }
  ],
  "augmentations": {
    "SystemName": "Eock Prau YY-S d3-1",
    "StarPos": [26250.0, -1275.15625, 19813.40625],
    "horizons": true,
    "odyssey": true
  }
}
```
It would probably simplify the senders code by having to do only one mutation on the entry.
In a near future, we could imagine a shared shape of this _augmentations_ object across several shemas.

**Comment by robbyxp1** [comment]
Changing what we have done on other schemas is just plain work. We can't force client updates, and we just make the EDDN receivers handle two types of the same message.

**Comment by Athanasius** [comment]
I've decided, rather than change even how a new schema is going to structure and name things, that we'll just document the need for location cross-checks (and any other such I come across whilst reviewing the current schemas and EDMC code).

There's some work on this already merged into the `develop` branch.

**Comment by Athanasius** [comment]
This has been live for a while now.
