### ISSUE TITLE
shipyard-v2.0.json missing event field in message object 

### ISSUE THREAD

**Issue by jixxed** [EDCD/EDDN#206]
this seems to not be in line with all the other messages

**Comment by Athanasius** [comment]
This is historical.

Originally there was no journal, and thus no events, only the CAPI endpoints.  Several of the EDDN schemas are thus based on CAPI data, not Journal data: `commodity`, `shipyard`, `outfitting`.

Given the *contents* are also in the CAPI format I don't see any benefit to adding the Journal-based `event` key:value to any of those three schemas.  It would be misleading.
