### ISSUE TITLE
ScanOrganic Schema

### ISSUE THREAD

**Issue by NoFoolLikeOne** [EDCD/EDDN#212]
An issue with collecting Biology data using the CodexEntry event is that users were unaware that you needed to use the Composition Scanner to record the Variety.

With Update 15 the Variety is stored in the ScanOrganic event which means that it is now possible to capture the variety without doing a composition scan. 

`{"Body": 16,  "Genus": "$Codex_Ent_Bacterial_Genus_Name;", "event": "ScanOrganic",  "Species": "$Codex_Ent_Bacterial_04_Name;", "Variant": "$Codex_Ent_Bacterial_04_Ruthenium_Name;", "ScanType": "Sample", "timestamp": "2023-05-10T08:34:40Z", "SystemAddress": 6681056514762,  "Genus_Localised": "Bacterium", "Species_Localised": "Bacterium Acies", "Variant_Localised": "Bacterium Acies - Cobalt"}`

I would like to keep the localised values  for translation and it may help in the event that frontier have given the wrong Variant.
I would like the BodyName added as an enhancement. 
"Body": should always be sent even if the BodyName enhancement is not possible.
I would like to capture Latitude and Longitude if possible to aid people in relocating the samples but this will not be possible for the likes of JournalLimpet so will need to be optional.

There can be an issue where the user has boarded their ship before the scanner animation has completed and so the Analyse ScanType can be generated on the wrong body when they take out the tool. I think ideally we should send the event but Caveat Emptor. Or we can specify that only Sample and Log Events should be sent.

**Comment by Tkael** [comment]
It seems like it would be fairly simple to require that clients check that `Analyse` scans have the same `SystemAddress` and `Body` as a prior scan for the same `Genus` (as long as a prior values have been recorded  during that play session). This may lead to some dropped `Analyse` scans but we'd probably still be able to capture the majority of them.

Or am I misunderstanding the nature of the bug?

**Comment by NoFoolLikeOne** [comment]
I'm not 100% sure. I should be able to find some examples or reproduce the issue. I'll do that today

**Comment by Silarn** [comment]
I hadn't read this prior to PRing the schema. Not sure how others feel about recording localization data, I followed the example of other schemas and excluded it for now.

I wasn't sure, but @NoFoolLikeOne indicated the body and system ID were reported correctly by delayed 'Analyse' scans. So we could potentially allow those provided augmentation data is cross checked as mentioned.

I'll make any changes as needed if there's a general consensus.
