### ISSUE TITLE
Send information on Trade Events - Marketbuy/sell

### ISSUE THREAD

**Issue by Berbe** [EDCD/EDDN#66]
Would it be possible to add events to the Journal schema (or create a dedicated one?) to handle market trade events (MarketBuy & MarketSell)?

More than commodities price, that would give an idea of volume exchanges and allow for some nice consequences:
- Predicting market prices variations on next update
- Best trades discovery, universe-wise (leaderboard?)
- Track Community Goal participation & stats estimations (since missing the individual sign-up status): near-realtime participants, overall progress, tiers' progress, tier's threshold, etc.
- ... any other market stats based on individual transactions collection you might imagine! :)

**Comment by Athanasius** [comment]
(Yes, I know this is now almost 3 years old).

I suspect the answer is no because EDDN isn't meant to relay any personal information, and actual buying and selling of commodities is personal.

You could look into implementing it as an EDMC Plugin sending data to your own server though.

**Comment by Berbe** [comment]
What do you mean by "personal information"?

**Comment by Athanasius** [comment]
You'd be able to correlate other events by the same uploaderID (it's obscured, and the key used to do this rotates, but that doesn't stop you doing so for a few hours per ID) with them buying and selling things.

*I* am not saying this is a valid reason to not add this, but usually Anthor is antsy about anything that even gets close to such.

As I said, it's the sort of thing you could write an EDMC plugin for.

**Comment by Tkael** [comment]
I actually think that these events are pretty safe from a personal information POV. And they could provide 3rd party websites with finer resolution on market data than they have now.

We currently typically see a snapshot of the market data when a commander first visits a website but we don't know (for example) if the commander made a significant dent in the demand / supply of a particular commodity during their visit.

**Comment by Berbe** [comment]
I would add that if the uploader ID is not tied to the user's name *and* it is being regularly rotated, even if specific actions are related to a specific user, it would only be during a limited time frame.
Moreover, I only target very specific events, meaning that if one user was to be stalked, it would only be through those actions.
Finally, all actions made by a user could allow the same, the solution here would be to stop uploading _any_ piece of data; there is nothing specific to the proposal, which does not particularly endanger anyone's privacy more than other pieces of information.

**Comment by Uriei** [comment]
I'm resurrecting this to ask about the "CommunityGoal" event, I could understand the other events that might send personal data in some instances, but this specific event is Community-wide and has zero personal data from the uploader, could this one be added at some point?

**Comment by Athanasius** [comment]
Is there really any information available from `CommunityGoal` events that isn't also available from https://api.orerve.net/2.0/website/initiatives/list?lang=en (use 'Accept: text/xml' header for a more computer-readable format) ?

I'm not sure if the current data from that endpoint has no tier information just because these CGs have/had no tiers (i.e. just a single objective).

**Comment by Uriei** [comment]
Oh, I didn't even know that api existed! Thank you very much!

**Comment by bgol** [comment]
> I'm not sure if the current data from that endpoint has no tier information just because these CGs have/had no tiers (i.e. just a single objective).

Afair, Tier information is only available in the journal event if you have joined the CG.

**Comment by Athanasius** [comment]
> > I'm not sure if the current data from that endpoint has no tier information just because these CGs have/had no tiers (i.e. just a single objective).
> 
> Afair, Tier information is only available in the journal event if you have joined the CG.

I was referring to the output of that API endpoint I quoted above:
```json
{
      "activityType": "tradelist",
      "bulletin": "Two ... shortly afterwards.\n",
      "expiry": "2023-02-02 07:00:00",
      "id": "765",
      "images": "NewsImageMarket",
      "market_name": "Schirra Dock",
      "news": "Enhanced AX Project: AX Missile Rack Fixed\n\nTwo leading e...megaships shortly afterwards.\n\n{{top5}}",
      "objective": "Gallium, Copper, Polymers, Advanced Catalysers, Synthetic Reagents",
      "qty": "916730",
      "starsystem_name": "Kappa Reticuli",
      "target_commodity_list": "Gallium, Copper, Polymers, Advanced Catalysers, Synthetic Reagents",
      "target_qty": "13000000",
      "title": "Development of Enhanced AX Missile Rack (Fixed)"
    }
```
i.e. does this only have information for whatever tier is current/last reached, or is it just that *these* CGs only have one tier ?

If, when there is definitely more than one tier, that API endpoint doesn't contain that information, then the Journal-sourced data *might* have some utility.

Looking at the Inara API docs and EDMC code relating to that, there's definitely information about tiers in the Journal events.

**Comment by bgol** [comment]
I updated my previous comment with two examples. There is no tier information in the web-api response, only in the journal one.

**Comment by Berbe** [comment]
It would be better if the title was reverted to reflect the actual, original requests, with my last message having remained unanswered.
It would have been better if @Uriei started a seperate thread for a seperate request, and @Athanasius to recognises subjets being different, the title not matching the new question, a split was to be requested to the new requestor.

**Comment by Athanasius** [comment]
If we're going down that route, then this issue gets simply closed.  As I said above, sending actual MarketBuy/MarketSell events is too close to Personal Information, and thus not for EDDN.

**Comment by robbyxp1** [comment]
Reverted title.
So, this is a very old request, which we have rejected, as it contains personal info, so lets close.
